[package]
name = "evol_heuristics"
version = "0.1.0"
edition = "2021"

[dependencies]
decorum = "0.4.0"
heuristics = { git = "https://github.com/VencaH/heuristics.git", branch = "task_2", version = "0.1.1" }
itertools = "0.14.0"
